### ISSUE TITLE
Click the close call a route automatically.

### ISSUE THREAD

**Issue by migueldaipre** [pankod/react-native-picker-modal-view#11]
I have the following scenario: I have a Categories route that in my react navigation header I make the call to the modal picker, but when I click the close icon of the modal picker it calls the next route automatically, and causes an error in my application, because this route must only be called by passing an object.

**Comment by omeraplak** [comment]
Hi @migueldaipre  ,
Thanks for helps. We want to fix it but we can't reproduce this bug. Could you share more information or example project for to reproduce this bug.

**Comment by migueldaipre** [comment]
When clicking the close button it also calls the onSelected function, below my code below.

`<PickerModal
  renderSelectView={(disabled, selected, showModal) =>
    <Button disabled={disabled} title={"Show me!"} onPress={showModal} />
  }
  onSelected={() => console.log('OnSelected call')}
  onClosed={() => console.log('onClosed call')} // close request
  onBackButtonPressed={this.onBackRequest.bind(this)} // back key press trigger
  items={data}
  sortingLanguage={'tr'} // default alphabet sorting is tr
  showToTopButton={true} // show top to up button while pass the screen half
  selected={this.state.selectedItem}
  autoGenerateAlphabeticalIndex={true} // using first letter while auto generate alphabets array in data list
  selectPlaceholderText={'Choose one...'}
  onEndReached={() => console.log('list ended...')} // list end trigger
  searchPlaceholderText={'Search...'} // search box placeholder text
  requireSelection={false} // force select and user can not close modal, close button hidden
  autoSort={false} // generate sorting to use Name in data array
/>`

If possible test too. Thank you

**Comment by migueldaipre** [comment]
This happens even when doing Bind, just like in documentation.

**Comment by omeraplak** [comment]
Hi @migueldaipre ,
I understand your situation. Close button not only close modal but also clear selection. If you want to hide clear (close) button, you can set requireSelection property to false.

**Comment by migueldaipre** [comment]
Hi @omeraplak , sorry for the error, and thanks for the explanation.
