### ISSUE TITLE
modal doesn't show up ....

### ISSUE THREAD

**Issue by TrustOne** [pankod/react-native-picker-modal-view#24]
I'm  trying to using like this.
`
Big_category.forEach((each,index) => {
          BigCategory.push ({
            Name : each,
            Value : each,
            Code : doc.id,
            Id : index,
          });
`
what's wrong? because The BigCategory isn't match with JSON style?

**Comment by omeraplak** [comment]
Hi @TrustOne ,
Thanks for reaching us.
Could you share full code for this error?

**Comment by TrustOne** [comment]
> Hi @TrustOne ,
> Thanks for reaching us.
> Could you share full code for this error?

Thanks for reply, I'm  really sorry, 
It was my problem, I'll solve myself,

**Comment by omeraplak** [comment]
We are so glad that problem solved and that you've used this component. Feel free to contact us if you need anything.
