### ISSUE TITLE
Deprecated lifecycle methods

### ISSUE THREAD

**Issue by BT1987** [pankod/react-native-picker-modal-view#33]
Hi there! 

I have installed this module and it's working great. However, I get two warnings for deprecated lifecycle methods (I'm on React Native v0.60):

```
Warning: componentWillMount is deprecated and will be removed in the next major version. 
Use componentDidMount instead. 
As a temporary workaround, you can rename to UNSAFE_componentWillMount.
Please update the following components: ModalComponent

Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. 
Use static getDerivedStateFromProps instead.
Please update the following components: ModalComponent
```

Could you please solve this? Thanks in advance.

**Comment by omeraplak** [comment]
Hi @BT1987 ,
Thanks for reaching us. We have added this feature to our backlog. We’ll update it soon.

**Comment by biskuvit** [comment]
Hi @BT1987 ,
We’ve launched 1.2.6 version on NPM. Feel free to contact us if you need anything.
