### ISSUE TITLE
Modal props are not passed through

### ISSUE THREAD

**Issue by ashish-kale** [pankod/react-native-picker-modal-view#37]
When device orientation is changed on iOS, the modal remains in the old orientation
Modal props override can solve the issue using supportedOrientations prop of ModalProps

**Comment by ashish-kale** [comment]
@kozmonotselcuk @biskuvit Can you please check and merge and release new version for this?

**Comment by omeraplak** [comment]
Hi @ashish-kale ,
we’ve launched 1.2.7 version on NPM. Feel free to contact us if you need anything.

**Comment by ashish-kale** [comment]
@omeraplak I checked the 1.2.7 version, the package has my new source code, but the dist folder has old code. Can you please check?

**Comment by ashish-kale** [comment]
@omeraplak created #39 to build the included changes.Can you please release this?

**Comment by omeraplak** [comment]
Hi @ashish-kale ,
we’ve launched 1.2.8 version on NPM. Feel free to contact us if you need anything.
