### ISSUE TITLE
Search input text not displaying on iOS when Dark Mode is enabled

### ISSUE THREAD

**Issue by leemcmullen** [pankod/react-native-picker-modal-view#49]
Hello :-)

The search input text is rendering as white on iOS when dark mode is enabled. This PR seems to fix it: https://github.com/pankod/react-native-picker-modal-view/pull/44

Any idea if/when it will be merged and a new version released?

Thanks,
Lee

**Comment by omeraplak** [comment]
Hi @leemcmullen  ,
We've released 1.3.1 version. Thanks for your patience and your helps.
