### ISSUE TITLE
 I found a problem, when rolling out a picker modal or when I click on the alphabet order help me help ...

### ISSUE THREAD

**Issue by rafiafmar** [pankod/react-native-picker-modal-view#5]
I run the file :
https://github.com/pankod/react-native-picker-modal-view/tree/master/ExampleApp/App.js

![err](https://user-images.githubusercontent.com/29906491/57002424-c2e85b80-6bae-11e9-8409-4b6d8d9b223d.png)

**Comment by hamsddxn** [comment]
I have the same problem

**Comment by tubufeng** [comment]
maybe you can set:
 FlatListProps={{viewabilityConfig:{viewAreaCoveragePercentThreshold:50 }}}

**Comment by rafiafmar** [comment]
@tubufeng : 
Have you tried to run the project?
let me know if it works

**Comment by xjrimus** [comment]
It works, just set the FlatListProps Parameter. The PickerModal Tag can look like that:

`<PickerModal
          onSelected={(selected) => this.selected(selected)}	
          items={items}
          sortingLanguage={'en'}
          showToTopButton={true}
          selected={this.state.selectedItem}
          autoGenerateAlphabeticalIndex={true}
          selectPlaceholderText={'Choose one...'}
          onEndReached={() => console.log('list ended...')}
          searchPlaceholderText={'Search...'}
          requireSelection={false}
          autoSort={true}
          FlatListProps={{viewabilityConfig:{viewAreaCoveragePercentThreshold:50 }}}
          />`

**Comment by omeraplak** [comment]
Hi @rafiafmar @tubufeng @xjrimus ,
Thanks for helps. We want to fix it but we can't reproduce this bug. Could you share more information for reproduce this bug.

**Comment by xjrimus** [comment]
well, I did nothing but used the <PickerModal> tag with all the parameters like in your README, created a static Array and it worked. But when I chose the dropdown (so that the Screen hat to Rerender) I got the Error described here. The workaround is described above

**Comment by omeraplak** [comment]
Hi @xjrimus ,
We can't reproduce this bug with README of example code. We need more information for your environment. Thanks for helps.
* What is your react-native version?
* What are the details from which platform you got this bug? Ios/android os version, model etc...

**Comment by omeraplak** [comment]
Hi everyone,
We reproduced bug today and we are planning to fix tomorrow with 1.2.1 version. I will inform you when new version has been released. Thanks for your patience and your helps.

**Comment by omeraplak** [comment]
Hi everyone,
We fixed this issue today and released 1.2.2 version. Thanks for your patience and your helps.
