### ISSUE TITLE
Call the picker in the OnPress of a Button

### ISSUE THREAD

**Issue by migueldaipre** [pankod/react-native-picker-modal-view#6]
Is it possible from the click of a button to call the picker? Instead of showing an input with "Choose one ...".

**Comment by omeraplak** [comment]
Hi @migueldaipre ,
Thanks for reaching us. We have added this feature to our backlog. We’ll update it soon.

**Comment by omeraplak** [comment]
Hi @migueldaipre , 
we’ve launched 1.2.0 version on NPM. You can use "renderSelectView" property now. Feel free to contact us if you need anything.

**Comment by migueldaipre** [comment]
I'm happy with the speed of response and launch. Thank you
